# Generated by Django 2.2.3 on 2019-08-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(blank=True, null=True, verbose_name='timestamp')),
                ('uri', models.CharField(max_length=200)),
                ('status_code', models.PositiveSmallIntegerField(default=0)),
                ('username', models.CharField(max_length=200)),
            ],
        ),
    ]
