# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-09 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20170801_2332'),
        ('accounts', '0003_auto_20170801_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='assignment', ),
        migrations.AddField(
            model_name='user',
            name='delegate',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='delegate',
                to='core.Delegate'), ),
    ]
