# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-13 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20161202_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegate',
            name='published_summary',
            field=models.TextField(blank=True, default=b'', null=True),
        ),
    ]
