# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-26 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_delegate_published_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegate',
            name='voting',
            field=models.BooleanField(default=False),
        ),
    ]
