# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-01 23:32
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_delegate_voting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('num_beginner_delegates', models.PositiveSmallIntegerField()),
                ('num_intermediate_delegates', models.PositiveSmallIntegerField()),
                ('num_advanced_delegates', models.PositiveSmallIntegerField()),
                ('num_spanish_speaking_delegates', models.PositiveSmallIntegerField()),
                ('num_chinese_speaking_delegates', models.PositiveSmallIntegerField()),
                ('registration_comments', models.TextField(blank=True, default=b'')),
                ('is_waitlisted', models.BooleanField(default=False)),
                ('waivers_completed', models.BooleanField(default=False)),
                ('assignments_finalized', models.BooleanField(default=False)),
                ('fees_owed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('fees_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('committee_preferences', models.ManyToManyField(to='core.Committee')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.Conference')),
                ('country_preferences', models.ManyToManyField(through='core.CountryPreference', to='core.Country')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.School')),
            ],
            options={
                'db_table': 'registration',
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Registration'),
        ),
        migrations.AddField(
            model_name='countrypreference',
            name='registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Registration'),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set([('conference', 'school')]),
        ),
    ]
