# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-01 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('core', '0021_auto_20170801_1436'), ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set([('conference', 'school')]), ),
    ]
