# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-09 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20170806_2350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countrypreference',
            options={'ordering': ['-registration', 'rank']},
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='school',
        ),
        migrations.RemoveField(
            model_name='school',
            name='advanced_delegates',
        ),
        migrations.RemoveField(
            model_name='school',
            name='assignments_finalized',
        ),
        migrations.RemoveField(
            model_name='school',
            name='beginner_delegates',
        ),
        migrations.RemoveField(
            model_name='school',
            name='chinese_speaking_delegates',
        ),
        migrations.RemoveField(
            model_name='school',
            name='committeepreferences',
        ),
        migrations.RemoveField(
            model_name='school',
            name='countrypreferences',
        ),
        migrations.RemoveField(
            model_name='school',
            name='fees_owed',
        ),
        migrations.RemoveField(
            model_name='school',
            name='fees_paid',
        ),
        migrations.RemoveField(
            model_name='school',
            name='intermediate_delegates',
        ),
        migrations.RemoveField(
            model_name='school',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='school',
            name='registered',
        ),
        migrations.RemoveField(
            model_name='school',
            name='registration_comments',
        ),
        migrations.RemoveField(
            model_name='school',
            name='spanish_speaking_delegates',
        ),
        migrations.RemoveField(
            model_name='school',
            name='waitlist',
        ),
        migrations.RemoveField(
            model_name='school',
            name='waivers_completed',
        ),
        migrations.AlterUniqueTogether(
            name='countrypreference',
            unique_together=set([('country', 'registration')]),
        ),
        migrations.RemoveField(
            model_name='countrypreference',
            name='school',
        ),
    ]
