# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-27 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20170809_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegate',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
