# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-06 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20171105_1635'),
        ('core', '0025_auto_20171113_1803'),
    ]

    operations = [
    ]
