# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-06 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20171113_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to=b'position_papers/')),
                ('graded', models.BooleanField(default=False)),
                ('score_1', models.PositiveSmallIntegerField(default=0)),
                ('score_2', models.PositiveSmallIntegerField(default=0)),
                ('score_3', models.PositiveSmallIntegerField(default=0)),
                ('score_4', models.PositiveSmallIntegerField(default=0)),
                ('score_5', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'position_papers',
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_category_1', models.CharField(default=b'', max_length=128)),
                ('grade_category_2', models.CharField(default=b'', max_length=128)),
                ('grade_category_3', models.CharField(default=b'', max_length=128)),
                ('grade_category_4', models.CharField(default=b'', max_length=128)),
                ('grade_category_5', models.CharField(default=b'', max_length=128)),
                ('grade_value_1', models.PositiveSmallIntegerField(default=10)),
                ('grade_value_2', models.PositiveSmallIntegerField(default=10)),
                ('grade_value_3', models.PositiveSmallIntegerField(default=10)),
                ('grade_value_4', models.PositiveSmallIntegerField(default=10)),
                ('grade_value_5', models.PositiveSmallIntegerField(default=10)),
            ],
            options={
                'db_table': 'rubric',
            },
        ),
        migrations.AlterField(
            model_name='registration',
            name='committee_preferences',
            field=models.ManyToManyField(blank=True, to='core.Committee'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='paper',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.PositionPaper'),
        ),
        migrations.AddField(
            model_name='committee',
            name='rubric',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Rubric'),
        ),
    ]
