# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-29 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20171206_1716'),
        ('core', '0027_auto_20171229_1118'),
    ]

    operations = []
