# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-25 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('core', '0029_auto_20171229_1118'), ]

    operations = [
        migrations.AddField(
            model_name='positionpaper',
            name='submission_date',
            field=models.DateField(null=True), ),
    ]
