# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-31 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('core', '0029_position_paper_data'), ]

    operations = [
        migrations.AddField(
            model_name='positionpaper',
            name='score_t2_1',
            field=models.PositiveSmallIntegerField(default=0), ),
        migrations.AddField(
            model_name='positionpaper',
            name='score_t2_2',
            field=models.PositiveSmallIntegerField(default=0), ),
        migrations.AddField(
            model_name='positionpaper',
            name='score_t2_3',
            field=models.PositiveSmallIntegerField(default=0), ),
        migrations.AddField(
            model_name='positionpaper',
            name='score_t2_4',
            field=models.PositiveSmallIntegerField(default=0), ),
        migrations.AddField(
            model_name='positionpaper',
            name='score_t2_5',
            field=models.PositiveSmallIntegerField(default=0), ),
        migrations.AddField(
            model_name='rubric',
            name='grade_t2_category_1',
            field=models.CharField(
                default=b'', max_length=128), ),
        migrations.AddField(
            model_name='rubric',
            name='grade_t2_category_2',
            field=models.CharField(
                default=b'', max_length=128), ),
        migrations.AddField(
            model_name='rubric',
            name='grade_t2_category_3',
            field=models.CharField(
                default=b'', max_length=128), ),
        migrations.AddField(
            model_name='rubric',
            name='grade_t2_category_4',
            field=models.CharField(
                default=b'', max_length=128), ),
        migrations.AddField(
            model_name='rubric',
            name='grade_t2_category_5',
            field=models.CharField(
                default=b'', max_length=128), ),
        migrations.AddField(
            model_name='rubric',
            name='grade_t2_value_1',
            field=models.PositiveSmallIntegerField(default=10), ),
        migrations.AddField(
            model_name='rubric',
            name='grade_t2_value_2',
            field=models.PositiveSmallIntegerField(default=10), ),
        migrations.AddField(
            model_name='rubric',
            name='grade_t2_value_3',
            field=models.PositiveSmallIntegerField(default=10), ),
        migrations.AddField(
            model_name='rubric',
            name='grade_t2_value_4',
            field=models.PositiveSmallIntegerField(default=10), ),
        migrations.AddField(
            model_name='rubric',
            name='grade_t2_value_5',
            field=models.PositiveSmallIntegerField(default=10), ),
        migrations.AddField(
            model_name='rubric',
            name='topic_one',
            field=models.CharField(
                default=b'', max_length=64), ),
        migrations.AddField(
            model_name='rubric',
            name='topic_two',
            field=models.CharField(
                default=b'', max_length=64), ),
        migrations.AddField(
            model_name='rubric',
            name='use_topic_2',
            field=models.BooleanField(default=True), ),
    ]
