# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-01 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20180131_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='grade_category_1',
            field=models.CharField(blank=True, default=b'', max_length=128),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='grade_category_2',
            field=models.CharField(blank=True, default=b'', max_length=128),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='grade_category_3',
            field=models.CharField(blank=True, default=b'', max_length=128),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='grade_category_4',
            field=models.CharField(blank=True, default=b'', max_length=128),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='grade_category_5',
            field=models.CharField(blank=True, default=b'', max_length=128),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='grade_t2_category_1',
            field=models.CharField(blank=True, default=b'', max_length=128),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='grade_t2_category_2',
            field=models.CharField(blank=True, default=b'', max_length=128),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='grade_t2_category_3',
            field=models.CharField(blank=True, default=b'', max_length=128),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='grade_t2_category_4',
            field=models.CharField(blank=True, default=b'', max_length=128),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='grade_t2_category_5',
            field=models.CharField(blank=True, default=b'', max_length=128),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='topic_one',
            field=models.CharField(blank=True, default=b'', max_length=64),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='topic_two',
            field=models.CharField(blank=True, default=b'', max_length=64),
        ),
    ]
