# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-25 19:48
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('core', '0032_paper_data'), ]

    operations = [
        migrations.AddField(
            model_name='committeefeedback',
            name='chair_10_comment',
            field=models.TextField(
                blank=True, default=b''), ),
        migrations.AddField(
            model_name='committeefeedback',
            name='chair_10_name',
            field=models.CharField(
                blank=True, default=b'', max_length=100), ),
        migrations.AddField(
            model_name='committeefeedback',
            name='chair_10_rating',
            field=models.IntegerField(
                blank=True,
                choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5),
                         (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)],
                default=0), ),
        migrations.AddField(
            model_name='committeefeedback',
            name='chair_1_comment',
            field=models.TextField(
                blank=True, default=b''), ),
        migrations.AddField(
            model_name='committeefeedback',
            name='chair_1_name',
            field=models.CharField(
                blank=True, default=b'', max_length=100), ),
        migrations.AddField(
            model_name='committeefeedback',
            name='chair_1_rating',
            field=models.IntegerField(
                blank=True,
                choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5),
                         (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)],
                default=0), ),
        migrations.AddField(
            model_name='committeefeedback',
            name='chair_2_comment',
            field=models.TextField(
                blank=True, default=b''), ),
        migrations.AddField(
            model_name='committeefeedback',
            name='chair_2_name',
            field=models.CharField(
                blank=True, default=b'', max_length=100), ),
        migrations.AddField(
            model_name='committeefeedback',
            name='chair_2_rating',
            field=models.IntegerField(
                blank=True,
                choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5),
                         (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)],
                default=0), ),
        migrations.AddField(
            model_name='committeefeedback',
            name='chair_3_comment',
            field=models.TextField(
                blank=True, default=b''), ),
        migrations.AddField(
            model_name='committeefeedback',
            name='chair_3_name',
            field=models.CharField(
                blank=True, default=b'', max_length=100), ),
        migrations.AddField(
            model_name='committeefeedback',
            name='chair_3_rating',
            field=models.IntegerField(
                blank=True,
                choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5),
                         (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)],
                default=0), ),
        migrations.AddField(
            model_name='committeefeedback',
            name='chair_4_comment',
            field=models.TextField(
                blank=True, default=b''), ),
        migrations.AddField(
            model_name='committeefeedback',
            name='chair_4_name',
            field=models.CharField(
                blank=True, default=b'', max_length=100), ),
        migrations.AddField(
            model_name='committeefeedback',
            name='chair_4_rating',
            field=models.IntegerField(
                blank=True,
                choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5),
                         (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)],
                default=0), ),
        migrations.AddField(
            model_name='committeefeedback',
            name='chair_5_comment',
            field=models.TextField(
                blank=True, default=b''), ),
        migrations.AddField(
            model_name='committeefeedback',
            name='chair_5_name',
            field=models.CharField(
                blank=True, default=b'', max_length=100), ),
        migrations.AddField(
            model_name='committeefeedback',
            name='chair_5_rating',
            field=models.IntegerField(
                blank=True,
                choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5),
                         (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)],
                default=0), ),
        migrations.AddField(
            model_name='committeefeedback',
            name='chair_6_comment',
            field=models.TextField(
                blank=True, default=b''), ),
        migrations.AddField(
            model_name='committeefeedback',
            name='chair_6_name',
            field=models.CharField(
                blank=True, default=b'', max_length=100), ),
        migrations.AddField(
            model_name='committeefeedback',
            name='chair_6_rating',
            field=models.IntegerField(
                blank=True,
                choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5),
                         (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)],
                default=0), ),
        migrations.AddField(
            model_name='committeefeedback',
            name='chair_7_comment',
            field=models.TextField(
                blank=True, default=b''), ),
        migrations.AddField(
            model_name='committeefeedback',
            name='chair_7_name',
            field=models.CharField(
                blank=True, default=b'', max_length=100), ),
        migrations.AddField(
            model_name='committeefeedback',
            name='chair_7_rating',
            field=models.IntegerField(
                blank=True,
                choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5),
                         (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)],
                default=0), ),
        migrations.AddField(
            model_name='committeefeedback',
            name='chair_8_comment',
            field=models.TextField(
                blank=True, default=b''), ),
        migrations.AddField(
            model_name='committeefeedback',
            name='chair_8_name',
            field=models.CharField(
                blank=True, default=b'', max_length=100), ),
        migrations.AddField(
            model_name='committeefeedback',
            name='chair_8_rating',
            field=models.IntegerField(
                blank=True,
                choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5),
                         (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)],
                default=0), ),
        migrations.AddField(
            model_name='committeefeedback',
            name='chair_9_comment',
            field=models.TextField(
                blank=True, default=b''), ),
        migrations.AddField(
            model_name='committeefeedback',
            name='chair_9_name',
            field=models.CharField(
                blank=True, default=b'', max_length=100), ),
        migrations.AddField(
            model_name='committeefeedback',
            name='chair_9_rating',
            field=models.IntegerField(
                blank=True,
                choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5),
                         (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)],
                default=0), ),
        migrations.AddField(
            model_name='committeefeedback',
            name='rating',
            field=models.IntegerField(
                blank=True,
                choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5),
                         (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)],
                default=0), ),
        migrations.AlterField(
            model_name='committeefeedback',
            name='comment',
            field=models.TextField(
                blank=True, default=b''), ),
        migrations.AlterField(
            model_name='registration',
            name='delegate_fees_owed',
            field=models.DecimalField(
                decimal_places=2, default=Decimal('0.00'), max_digits=7), ),
        migrations.AlterField(
            model_name='registration',
            name='delegate_fees_paid',
            field=models.DecimalField(
                decimal_places=2, default=Decimal('0.00'), max_digits=7), ),
    ]
