# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-12-06 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('core', '0035_delegate_waiver_submitted'), ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='position_papers_accepted',
            field=models.BooleanField(default=False), ),
    ]
