# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-03 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('core', '0036_conference_position_papers_accepted'), ]

    operations = [
        migrations.AddField(
            model_name='positionpaper',
            name='graded_file',
            field=models.FileField(
                null=True, upload_to=b'graded_papers/'), ),
    ]
