# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-27 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_positionpaper_graded_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speechtype', models.PositiveSmallIntegerField(choices=[(0, b"Speaker's List"), (1, b'Moderated Caucus'), (2, b'Comment'), (3, b'Question'), (4, b'Formal')], default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Assignment')),
            ],
            options={
                'db_table': 'speech',
            },
        ),
        migrations.AlterField(
            model_name='positionpaper',
            name='graded_file',
            field=models.FileField(blank=True, null=True, upload_to=b'graded_papers/'),
        ),
    ]
