# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-27 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_positionpaper_graded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionpaper',
            name='graded_file',
            field=models.FileField(blank=True, null=True, upload_to=b'graded_papers/'),
        ),
    ]
