# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-31 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('core', '0037_positionpaper_graded_file'), ]

    operations = [
        migrations.CreateModel(
            name='InCommitteeFeedback',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('feedback', models.TextField()),
                ('score', models.IntegerField(
                    blank=True,
                    choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5),
                             (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)],
                    default=0)),
                ('assignment', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='core.Assignment')),
            ],
            options={
                'db_table': 'in_committee_feedback',
            }, ),
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
            ], ),
        migrations.AlterField(
            model_name='positionpaper',
            name='graded_file',
            field=models.FileField(
                blank=True, null=True, upload_to=b'graded_papers/'), ),
        migrations.AddField(
            model_name='incommitteefeedback',
            name='speech',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='core.Speech'), ),
    ]
