# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-27 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import huxley.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_positionpaper_graded_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speechtype', models.CharField(choices=[(b'CM', b'Comment'), (b'FM', b'Formal Caucus'), (b'MD', b'Moderated Caucus'), (b'QU', b'Question'), (b'SP', b"Speaker's List")], default=huxley.core.models.SpeechChoice(b"Speaker's List"), max_length=2)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Assignment')),
            ],
            options={
                'db_table': 'speech',
            },
        ),
        migrations.AlterField(
            model_name='positionpaper',
            name='graded_file',
            field=models.FileField(blank=True, null=True, upload_to=b'graded_papers/'),
        ),
    ]
