# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-27 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import huxley.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20190327_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speechtype', models.CharField(choices=[(huxley.core.models.SpeechChoice(b'Comment'), b'Comment'), (huxley.core.models.SpeechChoice(b'Formal Caucus'), b'Formal Caucus'), (huxley.core.models.SpeechChoice(b'Moderated Caucus'), b'Moderated Caucus'), (huxley.core.models.SpeechChoice(b'Question'), b'Question'), (huxley.core.models.SpeechChoice(b"Speaker's List"), b"Speaker's List")], max_length=1)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Assignment')),
            ],
        ),
    ]
