# Generated by Django 2.2.6 on 2020-08-17 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20200303_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='early_paper_deadline',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conference',
            name='paper_deadline',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
