# Generated by Django 2.2.6 on 2020-08-20 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_conference_treasurer'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='waiver_avail_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conference',
            name='waiver_deadline',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conference',
            name='waiver_link',
            field=models.CharField(default='www.bmun.org', max_length=300),
            preserve_default=False,
        ),
    ]
