# Generated by Django 2.2.6 on 2020-08-21 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20200821_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='round_four_end',
        ),
    ]
