# Generated by Django 2.2.6 on 2020-09-19 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_remove_conference_round_four_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='round_one_fees_due',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conference',
            name='round_two_fees_due',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
