# Generated by Django 2.2.6 on 2021-01-21 00:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='committee',
            name='zoom_link',
            field=models.URLField(default='https://zoom.us'),
        ),
        migrations.AddField(
            model_name='note',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='note',
            table='note',
        ),
    ]
