# Generated by Django 2.2.6 on 2021-02-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20210207_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='notes_activated',
            field=models.BooleanField(default=False),
        ),
    ]
