# Generated by Django 2.2.6 on 2021-02-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_committee_notes_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='notes_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
