# Generated by Django 2.2.6 on 2021-02-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_conference_notes_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='zoom_link',
            field=models.URLField(default='https://zoom.us'),
        ),
        migrations.AddField(
            model_name='conference',
            name='opi_link',
            field=models.URLField(default='https://zoom.us'),
        ),
    ]
