# Generated by Django 2.2.6 on 2021-02-24 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20210121_0014'),
        ('core', '0050_conference_notes_enabled'),
    ]

    operations = [
    ]
