# Generated by Django 2.2.6 on 2021-02-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_merge_20210224_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='opi_link',
            field=models.URLField(default='https://zoom.us'),
        ),
    ]
