# Generated by Django 2.2.6 on 2021-02-25 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20210225_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='zoom_link',
            field=models.URLField(default='https://zoom.us'),
        ),
    ]
