# Generated by Django 2.2.6 on 2021-02-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20210225_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='max_refresh_interval',
            field=models.PositiveIntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='conference',
            name='polling_interval',
            field=models.PositiveIntegerField(default=60000),
        ),
    ]
