# Generated by Django 2.2.6 on 2021-04-28 18:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_conference_note_checkpoint_padding'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='advisor_edit_deadline',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
