# Generated by Django 2.2.6 on 2021-12-27 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20210627_1313'),
        ('core', '0055_conference_advisor_edit_deadline'),
    ]

    operations = [
    ]
