# Generated by Django 2.2.6 on 2021-09-25 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_conference_advisor_edit_deadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delegate',
            options={'ordering': ['assignment']},
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='registration',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='rejected',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='committee_feedback_submitted',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='published_summary',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='school',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='session_four',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='session_one',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='session_three',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='session_two',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='voting',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='waiver_submitted',
        ),
    ]
