# Generated by Django 2.2.6 on 2021-12-27 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_merge_20211227_1531'),
        ('core', '0056_merge_20211227_1600'),
    ]

    operations = [
    ]
