# Generated by Django 2.2.6 on 2022-09-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20220116_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='payment_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Card'), (2, 'Check')], default=1),
        ),
    ]
