# Generated by Django 2.2.6 on 2022-09-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_registration_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='invoicing_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
