# Generated by Django 2.2.6 on 2021-12-28 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_waiver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Waiver',
        ),
    ]
