# Generated by Django 2.2.6 on 2022-09-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_conference_invoicing_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='invoices_sent',
            field=models.BooleanField(default=False),
        ),
    ]
