# Generated by Django 2.2.6 on 2023-02-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_registration_invoices_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeefeedback',
            name='conferences_attended',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='committeefeedback',
            name='other_events',
            field=models.IntegerField(blank=True, choices=[(0, 'Blank'), (1, 'Delegate Workshop Only'), (2, 'Fall Conference Only'), (3, 'Delegate Workshop and Fall Conference'), (4, 'Neither/I do not know what these are')], default=0),
        ),
        migrations.AddField(
            model_name='committeefeedback',
            name='outreach_sessions',
            field=models.IntegerField(blank=True, choices=[(0, 'Blank'), (1, 'No'), (2, 'Unsure'), (3, 'Yes')], default=0),
        ),
        migrations.AddField(
            model_name='committeefeedback',
            name='team_format',
            field=models.IntegerField(blank=True, choices=[(0, 'Blank'), (1, 'Club'), (2, 'Class'), (3, 'Other/unsure')], default=0),
        ),
        migrations.AlterField(
            model_name='committeefeedback',
            name='berkeley_perception',
            field=models.IntegerField(blank=True, choices=[(0, 'Blank'), (1, 'No'), (2, 'Unsure'), (3, 'Yes')], default=0),
        ),
    ]
