# Generated by Django 2.2.6 on 2021-12-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_waiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waiver',
            name='autotag',
        ),
        migrations.RemoveField(
            model_name='waiver',
            name='email',
        ),
        migrations.RemoveField(
            model_name='waiver',
            name='username',
        ),
        migrations.AddField(
            model_name='waiver',
            name='unique_id',
            field=models.CharField(default='hello', max_length=64),
            preserve_default=False,
        ),
    ]
