# Generated by Django 2.2.6 on 2022-01-31 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_auto_20211229_1617'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Waiver',
        ),
    ]
